---
abstract: 'A tiny plugin system for perl'
author:
  - 'Maurice Mengel <mauricemengel@gmail.com>'
build_requires:
  File::Spec: 0
  FindBin: 0
  Moo::Role: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plugin-Tiny
requires:
  Carp: 0
  Module::Runtime: 0
  Moo: 0
  MooX::Types::MooseLike::Base: 0
  Scalar::Util: 0
  namespace::clean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Plugin-Tiny
  homepage: https://github.com/mokko/p5-Plugin-Tiny/wiki
  repository: git://github.com/mokko/p5-Plugin-Tiny.git
version: 0.010
